### PR TITLE
Allow /_search/scroll endpoints

### PR DESCRIPTION
**Pull request by aolieman**
By allowing requests to the scroll endpoint, API users can more efficiently fetch the full set of results for a query. Currently, the scroll query can be initialized, but any result batches beyond the first cannot be requested/downloaded.

The GET and POST methods on this endpoint are used to fetch subsequent result batches. The DELETE method is needed to clear the search context whenever the user abandons the scrolled search, or when the available results have been exhausted. Without this DELETE request, the search context will take up some ES heap until the scroll times out.

### CODE REVIEW

**Comment by aolieman** [comment]
Longer term, the scroll endpoint could be deprecated in favor of the "search after" pattern:
https://www.elastic.co/guide/en/elasticsearch/reference/6.8/search-request-search-after.html

What we would need to test this is one of these mapping changes:
- let `@id` be an integer (so it can be sorted reliably)
- add a `processed_at` or `modified_at` datetime/timestamp that is only mutated when the doc is updated

There is some time pressure now to provide a solution that is more efficient than deep pagination (for the HierOverheid integration). Enabling scroll is the easy solution. If there are concerns with scroll for the longer term, search after may provide a suitable alternative.

**Comment by aolieman** [comment]
I noticed that there still is a problem with clearing scroll context, given the proposed endpoint changes. The examples from the elasticsearch docs (which are safe to try) don't all work properly.

```
$ ORI_ES_SCROLL="https://api.openraadsinformatie.nl:443/v1/elastic/_search/scroll"
$ curl -X DELETE "$ORI_ES_SCROLL?pretty" -H 'Content-Type: application/json' -d'
> {
>     "scroll_id" : "DXF1ZXJ5QW5kRmV0Y2gBAAAAAAAAAD4WYm9laVYtZndUQlNsdDcwakFMNjU1QQ=="
> }
> '
{
 "code": 5,
 "message": "Method does not exist.",
 "details": [
  {
   "@type": "type.googleapis.com/google.rpc.DebugInfo",
   "stackEntries": [],
   "detail": "service_control"
  }
 ]
}

$ curl -X DELETE "$ORI_ES_SCROLL?pretty" -H 'Content-Type: application/json' -d'
> {
>     "scroll_id" : [
>       "DXF1ZXJ5QW5kRmV0Y2gBAAAAAAAAAD4WYm9laVYtZndUQlNsdDcwakFMNjU1QQ==",
>       "DnF1ZXJ5VGhlbkZldGNoBQAAAAAAAAABFmtSWWRRWUJrU2o2ZExpSGJCVmQxYUEAAAAAAAAAAxZrUllkUVlCa1NqNmRMaUhiQlZkMWFBAAAAAAAAAAIWa1JZZFFZQmtTajZkTGlIYkJWZDFhQQAAAAAAAAAFFmtSWWRRWUJrU2o2ZExpSGJCVmQxYUEAAAAAAAAABBZrUllkUVlCa1NqNmRMaUhiQlZkMWFB"
>     ]
> }
> '
{
 "code": 5,
 "message": "Method does not exist.",
 "details": [
  {
   "@type": "type.googleapis.com/google.rpc.DebugInfo",
   "stackEntries": [],
   "detail": "service_control"
  }
 ]
}
```

The issue with these requests is that path parameters in Swagger are always required. I forgot about this and declared it optional anyway, which causes the above error message instead of a more informative one.

```
$ curl -X DELETE "$ORI_ES_SCROLL/DXF1ZXJ5QW5kRmV0Y2gBAAAAAAAAAD4WYm9laVYtZndUQlNsdDcwakFMNjU1QQ==,DnF1ZXJ5VGhlbkZldGNoBQAAAAAAAAABFmtSWWRRWUJrU2o2ZExpSGJCVmQxYUEAAAAAAAAAAxZrUllkUVlCa1NqNmRMaUhiQlZkMWFBAAAAAAAAAAIWa1JZZFFZQmtTajZkTGlIYkJWZDFhQQAAAAAAAAAFFmtSWWRRWUJrU2o2ZExpSGJCVmQxYUEAAAAAAAAABBZrUllkUVlCa1NqNmRMaUhiQlZkMWFB?pretty"
{
  "succeeded" : true,
  "num_freed" : 0
}
```

That explains why the query above works, but the one below doesn't:

```
$ curl -X DELETE "$ORI_ES_SCROLL/?pretty&scroll_id=DXF1ZXJ5QW5kRmV0Y2gBAAAAAAAAAD4WYm9laVYtZndUQlNsdDcwakFMNjU1QQ=="
{
 "code": 5,
 "message": "Method does not exist.",
 "details": [
  {
   "@type": "type.googleapis.com/google.rpc.DebugInfo",
   "stackEntries": [],
   "detail": "service_control"
  }
 ]
}
```

Funnily enough, elasticsearch will accept and ignore made-up path suffixes:

```
$ curl -X DELETE "$ORI_ES_SCROLL/dummy?pretty" -H 'Content-Type: application/json' -d'
> {
>     "scroll_id" : "DXF1ZXJ5QW5kRmV0Y2gBAAAAAAAAAD4WYm9laVYtZndUQlNsdDcwakFMNjU1QQ=="
> }
> '
{
  "succeeded" : true,
  "num_freed" : 0
}
```

It took me a while to find this issue because the default ES client in python (using the `scan` helper function) tries to clear scroll contexts using the first (non-working) method, but also ignores 404 responses. This is probably also the case for other ES clients because scroll IDs may have already timed out when attempting to clear them, and all the "working" examples above returned 404 as well.

I think the desired result is that all above methods for clearing a scroll context work. Before other people get confused, or worse, leave open scroll contexts because their client thinks they were successfully closed.

Since Swagger is strict about path parameters, I think the `/_search/scroll/{scrollId}:` path needs to be duplicated to `/_search/scroll:`. Is it allowed/possible to do this neatly with a yaml anchor and alias?

**Comment by jurrian** [comment]
> What we would need to test this is one of these mapping changes:
> 
> * let `@id` be an integer (so it can be sorted reliably)

`@id` has to be a string in order to be converted to a IRI in Json-LD.

> * add a `processed_at` or `modified_at` datetime/timestamp that is only mutated when the doc is updated

These are currently scheduled for milestone 1.6.0

**Comment by jurrian** [comment]
I made some changes to make the /_search/scroll endpoint work. The examples described in this comment https://github.com/openstate/open-raadsinformatie/pull/296#issuecomment-565862388 work now and tested.

Since I cannot commit to this remote fork, I can't merge this PR. I have created a new PR #306 where this will be continued.

**Comment by aolieman** [comment]
Thanks for the quick resolution @jurrian !

I keep checking the "allow edits from maintainers" box, but for `WaarOverheid:feature/` branches the box is unchecked again when I refresh the PR page. I'll try to remember to submit PRs from non-organization repos in the future.

**Pull request closed without merging**
